sudo: false

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
  - php: 7.1
    env: WP_TRAVISCI=travis:phpvalidate
  - php: 7.1
    env: WP_TRAVISCI=travis:codecoverage
  - php: 7.1
    env: WP_TRAVISCI=travis:jshint
  - php: 7.1
    env: WP_TRAVISCI=travis:phpunit WP_VERSION=nightly
  - php: 7.1
    env: WP_TRAVISCI=travis:phpunit
  - php: 7.0
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.6
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.5
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.4
    env: WP_TRAVISCI=travis:phpunit
  - php: 5.3
    env: WP_TRAVISCI=travis:phpunit
  - php: hhvm
    env: WP_TRAVISCI=travis:phpunit
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  apt: true
  bundler: true
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require phpmd/phpmd
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    composer install --no-interaction
  - |
    if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
      npm install
      node --version
      npm --version
      grunt --version
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      grunt checktextdomain
      phpmd classes text codesize,naming,unusedcode
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
      phpunit --coverage-clover build/logs/clover.xml
    else
      phpunit
    fi
  - |
   if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
     grunt jshint
   fi

after_script:
  # Push coverage off to Codecov
- |
  if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  slack:
    rooms:
      secure: AZ/PvqIs/pQnLODxLMPzbydUyc0GPEUsktn8gPRXQP5e1sIsmz50zod0fAgA8PgkMZt8myz72v5bWjx22y+nvAcuhTb8ZdX7ub+QJzOkuCpL1rZ7Y26gp17GxFY3iASJCVNidq3rRP1tO1iYunkXXwnibCgz/A09g7n+Lw5vm10zsWIKQ2/2lr542ey09wrUhSyxWmxiN0v5nDVKwhlvsw8feV46X+ibLYNrUa/ybX/nePyEvR0cyBKi/A7QBn4VPb44HSr78U1GwWMsbuxqMWm5ChFBlwvBMMSJz41h/z2LAQZ/WISUfPqNVO359r/TeVkMWEhIg8VawS3MqgQHt04OLrDGCxO/mtqRMbV+qVgpFiSW/GkfMiLzhuia4M0etiz+ZxazeoJcT7rwZ4dUmWtsIZr9oQQxvYW82XMNEpzayO7OVFBag38uquu+YMGepvZdnvv/WB7EfrOlEVeb9hAHSL7gjyYdFGDEHBOLyoTleOX+T8uHtudsIRpnO16IKeAsx+Z3VsMxngCasXT3PAz+DYoW/bc5j/lsE9LLyXREEifRA4COiarRvqyVA2CqQrED8w8Uff8nbInHo7UkKw6+o8poJntIvkvQauPpHfscN2RfFdwBtNZrz46nIAep8git/iTrIweCG7lrnZMuN3XPH7+BGoq61ZYFqHweDX0=
    on_start: never
    on_failure: always
    on_success: change
